title: Healthchecker
description: HealthChecker para validar estado de los microservicios de "SocioUnido"
theme: just-the-docs

url: "https://trabajoprofesional-aggz.github.io"

baseurl: "/healthchecker"
